id: P12B1171F
initial_creation_type: input
source_metadata:
  title: Copper-Coloured Mountain
  language: fr
  description: 'Texts related to the Copper-Coloured Mountain of Glory (zangs mdog
    dpal ri), the heaven of Guru Padmasambhava:'
  volume:
    2d7e2d11349541e5889aeb618e07527f:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Aspiration Prayers
    391eba72f8534c71aae47e4960ae8444:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Aspiration Prayers
    31c1cfaa17424194baacff3836586bcf:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Aspiration Prayers
    f4d1575c6a774abc8348a48913f24a49:
      title: A Prayer of Aspiration for the Mountain of Glory
      parent: Aspiration Prayers
    4ec7dc8978f640fead36f12e477c64a7:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Aspiration Prayers
    477eaf846aef4f88ab5234a66215bae0:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Aspiration Prayers
    24e765294c74420cbca65f9495845853:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      parent: Aspiration Prayers
created_at: '2022-03-01T03:20:07.633415'
last_modified_at: '2022-03-01T03:20:07.633418'
